#Extracción del Archivo Tratado

Carga el archivo CSV que contiene los datos tratados anteriormente.
📂 Atención: Utiliza el mismo archivo que limpiaste y organizaste en la Parte 1 del desafío Telecom X. Debe contener solo las columnas relevantes, ya con los datos corregidos y estandarizados.

In [12]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [13]:
datos = pd.read_csv('/content/TelecomX_Data.csv')
datos.sample(5)

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
709,1045-LTCYT,No,Female,0,Yes,Yes,8,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card (automatic),21.05,139.75
6406,9089-UOWJG,No,Female,0,Yes,Yes,12,Yes,No,DSL,...,No,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),58.35,740.55
3726,5256-SKJGO,No,Female,0,Yes,Yes,64,No,No phone service,DSL,...,Yes,No,Yes,Yes,Yes,Two year,Yes,Electronic check,54.60,3423.50
3388,4824-GUCBY,No,Female,1,No,No,22,Yes,No,Fiber optic,...,Yes,No,No,No,No,Month-to-month,No,Electronic check,81.70,1820.90
1664,2428-ZMCTB,No,Male,0,No,No,10,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card (automatic),19.75,208.25

In [14]:
datos.shape

(7032, 21)

In [15]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7032 non-null   object
 1   Churn                      7032 non-null   object
 2   customer.gender            7032 non-null   object
 3   customer.SeniorCitizen     7032 non-null   int64
 4   customer.Partner           7032 non-null   object
 5   customer.Dependents        7032 non-null   object
 6   customer.tenure            7032 non-null   int64
 7   phone.PhoneService         7032 non-null   object
 8   phone.MultipleLines        7032 non-null   object
 9   internet.InternetService   7032 non-null   object
 10  internet.OnlineSecurity    7032 non-null   object
 11  internet.OnlineBackup      7032 non-null   object
 12  internet.DeviceProtection  7032 non-null   object
 13  internet.TechSupport       7032 non-null   object
 14  internet.StreamingTV       7032 non-null   object
 15  internet.StreamingMovies   7032 non-null   object
 16  account.Contract           7032 non-null   object
 17  account.PaperlessBilling   7032 non-null   object
 18  account.PaymentMethod      7032 non-null   object
 19  account.Charges.Monthly    7032 non-null   float64
 20  account.Charges.Total      7032 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [16]:
datos.columns

Index(['customerID', 'Churn', 'customer.gender', 'customer.SeniorCitizen',
       'customer.Partner', 'customer.Dependents', 'customer.tenure',
       'phone.PhoneService', 'phone.MultipleLines', 'internet.InternetService',
       'internet.OnlineSecurity', 'internet.OnlineBackup',
       'internet.DeviceProtection', 'internet.TechSupport',
       'internet.StreamingTV', 'internet.StreamingMovies', 'account.Contract',
       'account.PaperlessBilling', 'account.PaymentMethod',
       'account.Charges.Monthly', 'account.Charges.Total'],
      dtype='object')

#Eliminación de Columnas Irrelevantes

Elimina columnas que no aportan valor al análisis o a los modelos predictivos, como identificadores únicos (por ejemplo, el ID del cliente). Estas columnas no ayudan en la predicción de la cancelación y pueden incluso perjudicar el desempeño de los modelos.

In [17]:
datos = datos.drop(columns = 'customerID')

In [18]:
datos.head()

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40

In [19]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Churn                      7032 non-null   object
 1   customer.gender            7032 non-null   object
 2   customer.SeniorCitizen     7032 non-null   int64
 3   customer.Partner           7032 non-null   object
 4   customer.Dependents        7032 non-null   object
 5   customer.tenure            7032 non-null   int64
 6   phone.PhoneService         7032 non-null   object
 7   phone.MultipleLines        7032 non-null   object
 8   internet.InternetService   7032 non-null   object
 9   internet.OnlineSecurity    7032 non-null   object
 10  internet.OnlineBackup      7032 non-null   object
 11  internet.DeviceProtection  7032 non-null   object
 12  internet.TechSupport       7032 non-null   object
 13  internet.StreamingTV       7032 non-null   object
 14  internet.StreamingMovies   7032 non-null   object
 15  account.Contract           7032 non-null   object
 16  account.PaperlessBilling   7032 non-null   object
 17  account.PaymentMethod      7032 non-null   object
 18  account.Charges.Monthly    7032 non-null   float64
 19  account.Charges.Total      7032 non-null   float64
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

####Separación por variables

In [24]:
var_numerica = datos[['customer.SeniorCitizen','customer.tenure','account.Charges.Monthly','account.Charges.Total']]
var_numerica.head()

,customer.SeniorCitizen,customer.tenure,account.Charges.Monthly,account.Charges.Total
0,0,9,65.6,593.30
1,0,9,59.9,542.40
2,0,4,73.9,280.85
3,1,13,98.0,1237.85
4,1,3,83.9,267.40

In [26]:
var_categorica = datos.drop(columns = var_numerica.columns)
var_categorica

,Churn,customer.gender,customer.Partner,customer.Dependents,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod
0,No,Female,Yes,Yes,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check
1,No,Male,No,No,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check
2,Yes,Male,No,No,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check
3,Yes,Male,Yes,No,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check
4,Yes,Female,Yes,No,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,No,Female,No,No,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check
7028,Yes,Male,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check
7029,No,Male,No,No,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
7030,No,Male,Yes,Yes,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check
7031,No,Male,Yes,Yes,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check

In [42]:
var_categorica = var_categorica.drop(columns = 'Churn')

In [36]:
var_numerica['Churn'] = datos['Churn'].map({'Yes': 1, 'No': 0})

/tmp/ipykernel_267/3564125038.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  var_numerica['Churn'] = datos['Churn'].map({'Yes': 1, 'No': 0})

###Correlación

In [37]:
corr_num = var_numerica.corr()
corr_num

,customer.SeniorCitizen,customer.tenure,account.Charges.Monthly,account.Charges.Total,Churn
customer.SeniorCitizen,1.000000,0.015683,0.219874,0.102411,0.150541
customer.tenure,0.015683,1.000000,0.246862,0.825880,-0.354049
account.Charges.Monthly,0.219874,0.246862,1.000000,0.651065,0.192858
account.Charges.Total,0.102411,0.825880,0.651065,1.000000,-0.199484
Churn,0.150541,-0.354049,0.192858,-0.199484,1.000000

In [39]:
datos.columns

Index(['Churn', 'customer.gender', 'customer.SeniorCitizen',
       'customer.Partner', 'customer.Dependents', 'customer.tenure',
       'phone.PhoneService', 'phone.MultipleLines', 'internet.InternetService',
       'internet.OnlineSecurity', 'internet.OnlineBackup',
       'internet.DeviceProtection', 'internet.TechSupport',
       'internet.StreamingTV', 'internet.StreamingMovies', 'account.Contract',
       'account.PaperlessBilling', 'account.PaymentMethod',
       'account.Charges.Monthly', 'account.Charges.Total'],
      dtype='object')

In [40]:
datos = datos.drop(columns = ['account.Charges.Total'])

In [44]:
for col in var_categorica:
    print(f"\n Variable: {col}")
    display(pd.crosstab(datos[col], datos["Churn"], normalize="index") * 100)

 Variable: customer.gender

Churn                   No        Yes
customer.gender
Female           73.040482  26.959518
Male             73.795435  26.204565

 Variable: customer.Partner

Churn                    No        Yes
customer.Partner
No                67.023908  32.976092
Yes               80.282935  19.717065

 Variable: customer.Dependents

Churn                       No        Yes
customer.Dependents
No                   68.720860  31.279140
Yes                  84.468795  15.531205

 Variable: phone.PhoneService

Churn                      No        Yes
phone.PhoneService
No                  75.000000  25.000000
Yes                 73.252519  26.747481

 Variable: phone.MultipleLines

Churn                       No        Yes
phone.MultipleLines
No                   74.918759  25.081241
No phone service     75.000000  25.000000
Yes                  71.351534  28.648466

 Variable: internet.InternetService

Churn                            No        Yes
internet.InternetService
DSL                       81.001656  18.998344
Fiber optic               58.107235  41.892765
No                        92.565789   7.434211

 Variable: internet.OnlineSecurity

Churn                           No        Yes
internet.OnlineSecurity
No                       58.221333  41.778667
No internet service      92.565789   7.434211
Yes                      85.359801  14.640199

 Variable: internet.OnlineBackup

Churn                         No        Yes
internet.OnlineBackup
No                     60.058309  39.941691
No internet service    92.565789   7.434211
Yes                    78.432990  21.567010

 Variable: internet.DeviceProtection

Churn                             No        Yes
internet.DeviceProtection
No                         60.859729  39.140271
No internet service        92.565789   7.434211
Yes                        77.460711  22.539289

 Variable: internet.TechSupport

Churn                        No        Yes
internet.TechSupport
No                    58.352535  41.647465
No internet service   92.565789   7.434211
Yes                   84.803922  15.196078

 Variable: internet.StreamingTV

Churn                        No        Yes
internet.StreamingTV
No                    66.464934  33.535066
No internet service   92.565789   7.434211
Yes                   69.885313  30.114687

 Variable: internet.StreamingMovies

Churn                            No        Yes
internet.StreamingMovies
No                        66.271125  33.728875
No internet service       92.565789   7.434211
Yes                       70.047602  29.952398

 Variable: account.Contract

Churn                    No        Yes
account.Contract
Month-to-month    57.290323  42.709677
One year          88.722826  11.277174
Two year          97.151335   2.848665

 Variable: account.PaperlessBilling

Churn                            No        Yes
account.PaperlessBilling
No                        83.624302  16.375698
Yes                       66.410749  33.589251

 Variable: account.PaymentMethod

Churn                             No        Yes
account.PaymentMethod
Bank transfer (automatic)  83.268482  16.731518
Credit card (automatic)    84.746877  15.253123
Electronic check           54.714588  45.285412
Mailed check               80.798005  19.201995

In [45]:
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import chi2

datos_rank = datos.copy()
datos_rank["Churn"] = datos_rank["Churn"].map({"Yes": 1, "No": 0})
col_categorica = datos_rank.select_dtypes(include=["object"]).columns


le = LabelEncoder()
for col in col_categorica:
    datos_rank[col] = le.fit_transform(datos_rank[col])

X_cat = datos_rank[col_categorica]
y = datos_rank["Churn"]

chi_scores, p_values = chi2(X_cat, y)

chi_df = pd.DataFrame({
    "Variable": col_categorica,
    "Chi2 Score": chi_scores,
    "p-value": p_values
})

chi_df = chi_df.sort_values(by="Chi2 Score", ascending=False)

chi_df

                     Variable   Chi2 Score        p-value
12           account.Contract  1111.759054  9.186154e-244
6     internet.OnlineSecurity   550.437364  1.011220e-121
9        internet.TechSupport   522.164716  1.430807e-115
7       internet.OnlineBackup   229.441123   7.892689e-52
8   internet.DeviceProtection   190.688004   2.249863e-43
2         customer.Dependents   131.271509   2.159540e-30
13   account.PaperlessBilling   104.979224   1.234232e-24
1            customer.Partner    81.857769   1.462409e-19
14      account.PaymentMethod    59.240507   1.395318e-14
4         phone.MultipleLines     9.735960   1.806976e-03
5    internet.InternetService     9.715269   1.827433e-03
11   internet.StreamingMovies     8.357624   3.840725e-03
10       internet.StreamingTV     7.373234   6.620176e-03
0             customer.gender     0.254297   6.140655e-01
3          phone.PhoneService     0.092948   7.604618e-01

In [47]:
datos.columns

Index(['Churn', 'customer.gender', 'customer.SeniorCitizen',
       'customer.Partner', 'customer.Dependents', 'customer.tenure',
       'phone.PhoneService', 'phone.MultipleLines', 'internet.InternetService',
       'internet.OnlineSecurity', 'internet.OnlineBackup',
       'internet.DeviceProtection', 'internet.TechSupport',
       'internet.StreamingTV', 'internet.StreamingMovies', 'account.Contract',
       'account.PaperlessBilling', 'account.PaymentMethod',
       'account.Charges.Monthly'],
      dtype='object')

In [48]:
datos = datos.drop(columns = ['customer.gender', 'phone.PhoneService'])

Dividimos los datos en datos de prueba y de entrenamiento

In [49]:
X = datos.drop(columns = 'Churn')
y = datos['Churn']

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
    stratify=y, random_state=42
)

#Encoding

Transforma las variables categóricas a formato numérico para hacerlas compatibles con los algoritmos de machine learning. Utiliza un método de codificación adecuado, como one-hot encoding.

In [52]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [53]:
columnas = X.columns

In [56]:
one_hot = make_column_transformer((
    OneHotEncoder(drop = 'if_binary'),
    var_categorica
),
    remainder = 'passthrough',
    sparse_threshold=0,
    force_int_remainder_cols=False)